<a href="https://colab.research.google.com/github/vvardhan11/In-Class1/blob/main/Final_Code_5082.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
 
# reading csv file
data=pd.read_csv("DKSalaries (3).csv")

data=pd.DataFrame(data)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

%matplotlib inline

from urllib.request import urlopen
from bs4 import BeautifulSoup as bs
import re
import urllib

In [ ]:
url="https://www.actionnetwork.com/nba/injury-report"
user_agent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'
headers={'User-Agent':user_agent,} 

request=urllib.request.Request(url,None,headers) #The assembled request
response = urllib.request.urlopen(request)
soup=bs(response)
Injury_data=[]
title=soup.title
allrows=soup.find_all("tr")
for i in allrows:
    row_list=i.find_all("td")
    dataRow=[]
    for cell in row_list:
        dataRow.append(cell.text)
    Injury_data.append(dataRow)
df=pd.DataFrame(Injury_data)

In [ ]:
df = df.dropna(how='all')
new_columns = ['Name','Position','Status','Reason','Comment','date']

# assign new column names to the DataFrame
df.columns = new_columns

In [ ]:
options = ['Out' ,'Questionable']
filtered_df = df.loc[df['Status'].isin(options)]
#filtered_df = df.loc[df['Status'] == 'Out'] 
filtered_df.drop(columns=['Position','Reason','Comment','date'], inplace=True)
filtered_df

<ipython-input-5-a8af51af9bd2>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.drop(columns=['Position','Reason','Comment','date'], inplace=True)

                    Name        Status
2       Danilo Gallinari           Out
3    Robert Williams III           Out
4       Payton Pritchard           Out
6            Ben Simmons           Out
8            Cody Martin           Out
..                   ...           ...
107        Dalano Banton           Out
109      Jordan Clarkson           Out
110        Collin Sexton           Out
112           Kyle Kuzma           Out
113         Johnny Davis  Questionable

[81 rows x 2 columns]

In [ ]:
data=pd.merge(data, filtered_df, on="Name", how="left")
#data.merge(filtered_df[['*.S']].to_frame(), left_on='Name', right_index=True)
data

,Position,Name + ID,Name,ID,Roster Position,Salary,Game Info,TeamAbbrev,AvgPointsPerGame,Status
0,PF/C,Giannis Antetokounmpo (27089099),Giannis Antetokounmpo,27089099,PF/C/F/UTIL,12000,IND@MIL 03/16/2023 08:00PM ET,MIL,57.46,NaN
1,C,Nikola Jokic (27089103),Nikola Jokic,27089103,C/UTIL,11600,DEN@DET 03/16/2023 07:00PM ET,DEN,59.49,NaN
2,C,Domantas Sabonis (27089105),Domantas Sabonis,27089105,C/UTIL,10100,SAC@BKN 03/16/2023 07:30PM ET,SAC,48.17,NaN
3,PG/SG,Devin Booker (27089107),Devin Booker,27089107,PG/SG/G/UTIL,9900,ORL@PHX 03/16/2023 10:00PM ET,PHX,44.60,NaN
4,SF/PF,Kevin Durant (27089111),Kevin Durant,27089111,SF/PF/F/UTIL,9800,ORL@PHX 03/16/2023 10:00PM ET,PHX,49.68,Out
...,...,...,...,...,...,...,...,...,...,...
162,PG/SG,Michael Carter-Williams (27089626),Michael Carter-Williams,27089626,PG/SG/G/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,0.00,NaN
163,SG/SF,Kevon Harris (27089630),Kevon Harris,27089630,SG/SF/F/G/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,7.58,NaN
164,C,Goga Bitadze (27089635),Goga Bitadze,27089635,C/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,10.12,NaN
165,PF/C,Admiral Schofield (27089637),Admiral Schofield,27089637,PF/C/F/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,8.27,NaN
166,C,Jonathan Isaac (27089641),Jonathan Isaac,27089641,C/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,14.18,Out

In [ ]:
options = ['Out' ,'Questionable']
data = data.loc[~data['Status'].isin(options)]
#data = data.loc[data['Status'] != 'Out']
data

,Position,Name + ID,Name,ID,Roster Position,Salary,Game Info,TeamAbbrev,AvgPointsPerGame,Status
0,PF/C,Giannis Antetokounmpo (27089099),Giannis Antetokounmpo,27089099,PF/C/F/UTIL,12000,IND@MIL 03/16/2023 08:00PM ET,MIL,57.46,NaN
1,C,Nikola Jokic (27089103),Nikola Jokic,27089103,C/UTIL,11600,DEN@DET 03/16/2023 07:00PM ET,DEN,59.49,NaN
2,C,Domantas Sabonis (27089105),Domantas Sabonis,27089105,C/UTIL,10100,SAC@BKN 03/16/2023 07:30PM ET,SAC,48.17,NaN
3,PG/SG,Devin Booker (27089107),Devin Booker,27089107,PG/SG/G/UTIL,9900,ORL@PHX 03/16/2023 10:00PM ET,PHX,44.60,NaN
6,PG,Shai Gilgeous-Alexander (27089118),Shai Gilgeous-Alexander,27089118,PG/G/UTIL,9600,OKC@TOR 03/16/2023 07:30PM ET,OKC,50.22,NaN
...,...,...,...,...,...,...,...,...,...,...
161,SF/PF,Caleb Houstan (27089622),Caleb Houstan,27089622,SF/PF/F/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,7.90,NaN
162,PG/SG,Michael Carter-Williams (27089626),Michael Carter-Williams,27089626,PG/SG/G/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,0.00,NaN
163,SG/SF,Kevon Harris (27089630),Kevon Harris,27089630,SG/SF/F/G/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,7.58,NaN
164,C,Goga Bitadze (27089635),Goga Bitadze,27089635,C/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,10.12,NaN
165,PF/C,Admiral Schofield (27089637),Admiral Schofield,27089637,PF/C/F/UTIL,3000,ORL@PHX 03/16/2023 10:00PM ET,ORL,8.27,NaN

In [ ]:
pip install gurobipy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting gurobipy
  Downloading gurobipy-10.0.1-cp39-cp39-manylinux2014_x86_64.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 76.6 MB/s eta 0:00:00
Installing collected packages: gurobipy
Successfully installed gurobipy-10.0.1

In [ ]:
import pandas as pd
import gurobipy as gp
from gurobipy import GRB

# Define the positions we need to fill in the team
positions = ["PG", "SG", "SF", "PF", "C", "G", "F", "UTIL"]

# Define the salary cap
salary_cap = 50000

# Create the model
model = gp.Model("Basketball Team")

# Create variables for each player indicating whether they are on the team or not
team_players = model.addVars(data["Name + ID"], vtype=GRB.BINARY)

# Set the objective function to maximize the total points
model.setObjective(gp.quicksum(data.loc[data["Name + ID"] == player, "AvgPointsPerGame"].iloc[0] * team_players[player] for player in data["Name + ID"]), GRB.MAXIMIZE)

# Add constraint for the salary cap
model.addConstr(gp.quicksum(data.loc[data["Name + ID"] == player, "Salary"].iloc[0] * team_players[player] for player in data["Name + ID"]) <= salary_cap)

# Add constraints for the positions we need to fill
for position in positions:
    if position in "C":
        model.addConstr(gp.quicksum(team_players[player] for player in data.loc[data["Position"] == position, "Name + ID"]) <= 1)
    elif position == "G":
        model.addConstr(gp.quicksum(team_players[player] for player in data.loc[(data["Position"] == "PG") | (data["Position"] == "SG"), "Name + ID"]) <= 3)
    elif position == "F":
        model.addConstr(gp.quicksum(team_players[player] for player in data.loc[(data["Position"] == "SF") | (data["Position"] == "PF"), "Name + ID"]) <= 3)
    elif position == "UTIL":
        model.addConstr(gp.quicksum(team_players[player] for player in data["Name + ID"]) == 8)

# Optimize the model
model.optimize()

# Print the selected players, their positions, salaries, and final points
print("Selected players:")
total_salary = 0
total_points = 0
for player in data["Name + ID"]:
    if team_players[player].x > 0:
        position = data.loc[data["Name + ID"] == player, "Position"].iloc[0]
        salary = data.loc[data["Name + ID"] == player, "Salary"].iloc[0]
        points = data.loc[data["Name + ID"] == player, "AvgPointsPerGame"].iloc[0]
        print(f"{player}: {position} (${salary}): {points} points")
        total_salary += salary
        total_points += points

print(f"\nTotal salary: ${total_salary}")
print(f"Total points: {total_points:.2f}")

Restricted license - for non-production use only - expires 2024-10-28
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (linux64)

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 5 rows, 138 columns and 352 nonzeros
Model fingerprint: 0x945391bb
Variable types: 0 continuous, 138 integer (138 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+04]
  Objective range  [2e+00, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 5e+04]
Found heuristic solution: objective 127.0900000
Presolve removed 0 rows and 18 columns
Presolve time: 0.00s
Presolved: 5 rows, 120 columns, 298 nonzeros
Variable types: 0 continuous, 120 integer (120 binary)
Found heuristic solution: objective 265.7300000

Root relaxation: objective 2.805468e+02, 6 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  280.54678    0    2  265.73000  280.54678  5.58%     -    0s
H    0     0                     274.6100000  280.54678  2.16%     -    0s
H    0     0                     279.4900000  280.54678  0.38%     -    0s
     0     0  280.54678    0    2  279.49000  280.54678  0.38%     -    0s

Explored 1 nodes (6 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 2 (of 2 available processors)

Solution count 4: 279.49 274.61 265.73 127.09

Optimal solution found (tolerance 1.00e-04)
Best objective 2.794900000000e+02, best bound 2.794900000000e+02, gap 0.0000%
Selected players:
Nikola Jokic (27089103): C ($11600): 59.49 points
Shai Gilgeous-Alexander (27089118): PG ($9600): 50.22 points
Pascal Siakam (27089130): PF/C ($8400): 45.24 points
Aaron Gordon (27089206): PF ($6200): 32.6 points
Gary Trent Jr. (27089342): SG/SF ($4300): 27.68 points
Cameron Payne (27089412): PG ($3400): 22.63 points
Precious Achiuwa (27089451): SF ($3200): 20.59 points
Bol Bol (27089463): PF/C ($3100): 21.04 points

Total salary: $49800
Total points: 279.49